### ISSUE TITLE
Erro ao executar o mvn clean package 

### ISSUE THREAD

**Issue by AnselmoPfeifer** [decioluckow/javaparaweb2d#1]
Segue uma pare do erro do teste em capitulo16-projeto/

[ERROR] Failed to execute goal on project financeiro: Could not resolve dependencies for project javaparaweb:financeiro:war:0.0.1-SNAPSHOT: Failure to find org.springframework.security:facelets-taglib-jsf20-spring-3:jar:0.5 in https://maven.java.net/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jvnet-nexus-releases has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project financeiro: Could not resolve dependencies for project javaparaweb:financeiro:war:0.0.1-SNAPSHOT: Failure to find org.springframework.security:facelets-taglib-jsf20-spring-3:jar:0.5 in https://maven.java.net/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jvnet-nexus-releases has elapsed or updates are forced

**Comment by decioluckow** [comment]
Olá Anselmo,
A biblioteca facelets-taglib-jsf20-spring-3 foi removida do Google Code (onde também tinha o repositorio) para o github, mas ainda não foi colocada no repositorio central do maven.

Já entrei em contato com o produto da biblioteca, que disse que faria nos próximos dias, mas não ocorreu ainda. Conforme
https://github.com/domdorn/spring-security-facelets-taglib/issues/5

A solução é deixar de utiliza-la:
- remover o repositorio e dependencias do pom.xml
- remover a diretiva da taglib do cabeçalho do xhtml
- remover a tag e utilizar no lugar dela o seguinte:

`<h:panelGroup rendered="#{request.isUserInRole('ROLE_ADMINISTRADOR')}"> 
    <h:commandLink action="/admin/principal" title="Administrativo">
        <h:graphicImage library="imagens" name="administrativo16.png" />
    </h:commandLink>
</h:panelGroup>`

O efeito para o sistema será o mesmo...

Somente no capitulo 6 e 8 terá que ser feita esta alteração...

Me informe de alguma dificuldade adicional

**Comment by AnselmoPfeifer** [comment]
@decioluckow 
Seguindo as alterações citadas acima. Funcionou perfeitamente.
Obrigado.
